name: Makefile CI

on:
  push:
    branches: ["master", "beta", "stable"]
  pull_request:
  workflow_dispatch:

jobs:
  checkmake:
    name: Makefile Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - name: Install checkmake
        run: go install github.com/mrtazz/checkmake/cmd/checkmake@latest
      - name: Check makefile
        run: checkmake Makefile
