name: Continuous integration

on:
  push:
    branches: ["master", "beta", "stable"]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-nightly-unit-test:
    name: Rust unit test on nightly toolchain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - name: Run unit tests
        run: cargo test

  rust-stable-unit-test:
    name: Rust unit test on stable toolchain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Run unit tests
        run: cargo test

  rust-fmt:
    name: Rust format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt
      - name: Check format
        run: cargo fmt --all -- --check

  rust-clippy:
    name: Rust clippy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy
      - name: Check clippy
        run: cargo clippy --all-targets --all-features -- -D warning

  checkmake:
    name: Makefile Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - name: Install checkmake
        run: go install github.com/mrtazz/checkmake/cmd/checkmake@latest
      - name: Check makefile
        run: checkmake Makefile
