name: Nightly release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Release nightly version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
      - uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: Nightly ${{ steps.date.outputs.date }}
          tag_name: nightly-${{ steps.date.outputs.date }}
          generate_release_notes: true
